import jsPDF from 'jspdf';

export const generateInspectionReport = (data, imageUrl = null) => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  
  // Add header
  doc.setFontSize(24);
  doc.setTextColor(40, 53, 147);
  doc.text('Smart Building Inspection Report', pageWidth / 2, 20, { align: 'center' });
  
  // Add date
  doc.setFontSize(12);
  doc.setTextColor(0, 0, 0);
  doc.text(`Report Date: ${new Date().toLocaleDateString()}`, 20, 40);
  doc.text(`Report Time: ${new Date().toLocaleTimeString()}`, 20, 48);
  
  let yPos = 60;
  
  // Add damage summary
  doc.setFontSize(16);
  doc.text('Damage Analysis Summary', 20, yPos);
  yPos += 15;
  
  doc.setFontSize(12);
  if (Object.keys(data.detected_damages).length === 0) {
    doc.text('✅ No damages detected - Building is in good condition', 25, yPos);
    yPos += 10;
  } else {
    Object.entries(data.detected_damages).forEach(([damage, count], index) => {
      if (yPos > 280) {
        doc.addPage();
        yPos = 20;
      }
      const damageName = damage.replace('_', ' ').toUpperCase();
      doc.text(`• ${damageName}: ${count} instance(s)`, 25, yPos);
      yPos += 8;
    });
  }
  
  yPos += 10;
  
  // Add severity and health score
  doc.setFontSize(16);
  doc.text('Building Health Assessment', 20, yPos);
  yPos += 15;
  
  doc.setFontSize(12);
  doc.text(`Severity Level: ${data.severity}`, 25, yPos);
  yPos += 8;
  doc.text(`Health Score: ${data.health_score}/100`, 25, yPos);
  yPos += 15;
  
  // Add precautions
  doc.setFontSize(16);
  doc.text('Recommended Actions', 20, yPos);
  yPos += 15;
  
  doc.setFontSize(12);
  data.precautions.forEach((precaution, index) => {
    if (yPos > 280) {
      doc.addPage();
      yPos = 20;
    }
    doc.text(`${index + 1}. ${precaution}`, 25, yPos);
    yPos += 8;
  });
  
  // Add footer
  doc.setFontSize(10);
  doc.setTextColor(128, 128, 128);
  doc.text('Generated by Smart Building Inspection System', pageWidth / 2, 290, { align: 'center' });
  doc.text('Final Year Project | mAP: 89%', pageWidth / 2, 295, { align: 'center' });
  
  // Save PDF
  const fileName = `building-inspection-${Date.now()}.pdf`;
  doc.save(fileName);
  
  return fileName;
};